spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: Dlamini07

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
